rule test_meme_pwm:
    input:
        fasta="meme/pwm/test/promoters.fasta",
    output:
        pwm="pwm.txt",
        counts="counts.txt",
    log:
        "result/pwm.log",
    params:
        subseq=None,
        extra="",
    wrapper:
        # replace with "master/bio/meme/pwm" for submission to official snakemake-wrappers repo
        "https://raw.githubusercontent.com/MPUSP/mpusp-snakemake-wrappers/refs/heads/main/meme/pwm"
